# Importing Libraries 

In [2]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
                          

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')
%matplotlib inline
np.set_printoptions(suppress=True) # Suppress scientific notation where possible

In [4]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


# Data Cleaning

In [57]:
df_list = pd.read_csv('listings.csv', index_col=0)
#df_cal = pd.read_csv('calendar.csv', index_col=0)
#df_hoods = pd.read_csv('neighbourhoods.csv', index_col=0)
#df_reviews = pd.read_csv('reviews-2.csv', index_col=0)
# import re
# price of listing on a given night converted to float
test_df = df_list
df_list['price_n']=df_list['price'].str.extract(r'(\d+)')
df_list['price_n'] = pd.to_numeric(df_list['price_n'],errors='coerce')
#df_price = test_df.groupby(by='listing_id').sum()
#combined = pd.concat([df_list, df_price], axis=1)

In [58]:
#combined.head().reset_index(inplace=True)
combined.tail(50)

listing_url       scrape_id last_scraped  \
46902179  https://www.airbnb.com/rooms/46902179  20201210194816   2020-12-11   
46902714  https://www.airbnb.com/rooms/46902714  20201210194816   2020-12-11   
46903283  https://www.airbnb.com/rooms/46903283  20201210194816   2020-12-11   
46903319  https://www.airbnb.com/rooms/46903319  20201210194816   2020-12-11   
46904014  https://www.airbnb.com/rooms/46904014  20201210194816   2020-12-11   
46905076  https://www.airbnb.com/rooms/46905076  20201210194816   2020-12-11   
46906737  https://www.airbnb.com/rooms/46906737  20201210194816   2020-12-11   
46907503  https://www.airbnb.com/rooms/46907503  20201210194816   2020-12-11   
46907525  https://www.airbnb.com/rooms/46907525  20201210194816   2020-12-11   
46912055  https://www.airbnb.com/rooms/46912055  20201210194816   2020-12-11   
46912893  https://www.airbnb.com/rooms/46912893  20201210194816   2020-12-11   
46913475  https://www.airbnb.com/rooms/46913475  20201210194816   2020-12-11   
46913873  https://www.airbnb.com/rooms/46913873  20201210194816   2020-12-11   
46913994  https://www.airbnb.com/rooms/46913994  20201210194816   2020-12-11   
46916225  https://www.airbnb.com/rooms/46916225  20201210194816   2020-12-11   
46916495  https://www.airbnb.com/rooms/46916495  20201210194816   2020-12-11   
46916676  https://www.airbnb.com/rooms/46916676  20201210194816   2020-12-11   
46916754  https://www.airbnb.com/rooms/46916754  20201210194816   2020-12-11   
46916975  https://www.airbnb.com/rooms/46916975  20201210194816   2020-12-11   
46917210  https://www.airbnb.com/rooms/46917210  20201210194816   2020-12-11   
46919607  https://www.airbnb.com/rooms/46919607  20201210194816   2020-12-11   
46919915  https://www.airbnb.com/rooms/46919915  20201210194816   2020-12-11   
46920019  https://www.airbnb.com/rooms/46920019  20201210194816   2020-12-11   
46920641  https://www.airbnb.com/rooms/46920641  20201210194816   2020-12-11   
46920978  https://www.airbnb.com/rooms/46920978  20201210194816   2020-12-11   
46921598  https://www.airbnb.com/rooms/46921598  20201210194816   2020-12-11   
46921635  https://www.airbnb.com/rooms/46921635  20201210194816   2020-12-11   
46922095  https://www.airbnb.com/rooms/46922095  20201210194816   2020-12-11   
46923174  https://www.airbnb.com/rooms/46923174  20201210194816   2020-12-11   
46923243  https://www.airbnb.com/rooms/46923243  20201210194816   2020-12-11   
46923304  https://www.airbnb.com/rooms/46923304  20201210194816   2020-12-11   
46923545  https://www.airbnb.com/rooms/46923545  20201210194816   2020-12-11   
46924559  https://www.airbnb.com/rooms/46924559  20201210194816   2020-12-11   
46924834  https://www.airbnb.com/rooms/46924834  20201210194816   2020-12-11   
46926058  https://www.airbnb.com/rooms/46926058  20201210194816   2020-12-11   
46926885  https://www.airbnb.com/rooms/46926885  20201210194816   2020-12-11   
46927112  https://www.airbnb.com/rooms/46927112  20201210194816   2020-12-11   
46927620  https://www.airbnb.com/rooms/46927620  20201210194816   2020-12-11   
46927719  https://www.airbnb.com/rooms/46927719  20201210194816   2020-12-11   
46927925  https://www.airbnb.com/rooms/46927925  20201210194816   2020-12-11   
46929299  https://www.airbnb.com/rooms/46929299  20201210194816   2020-12-11   
46931266  https://www.airbnb.com/rooms/46931266  20201210194816   2020-12-11   
46932036  https://www.airbnb.com/rooms/46932036  20201210194816   2020-12-11   
46932330  https://www.airbnb.com/rooms/46932330  20201210194816   2020-12-11   
46935774  https://www.airbnb.com/rooms/46935774  20201210194816   2020-12-11   
46937371  https://www.airbnb.com/rooms/46937371  20201210194816   2020-12-11   
46937954  https://www.airbnb.com/rooms/46937954  20201210194816   2020-12-11   
46938514  https://www.airbnb.com/rooms/46938514  20201210194816   2020-12-11   
46938537  https://www.airbnb.com/rooms/46938537  20201210194816   2020-12-11   
46941857  https://www.airbnb.com/roo

In [65]:
fin = test_df[['host_is_superhost','neighbourhood','property_type','room_type','accommodates',
                'bedrooms','beds','amenities','price_n','number_of_reviews_ltm',
                'number_of_reviews_l30d','last_review','review_scores_rating','review_scores_accuracy',
                'review_scores_cleanliness','review_scores_checkin','review_scores_communication',
                'review_scores_location','review_scores_value']]
#fin.beds.value_counts()
fin.loc[[],['beds']]= 22704

/Users/jihyangseo/Desktop/GitGoods/miniconda3/envs/metis/lib/python3.8/site-packages/pandas/core/indexing.py:1719: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [43]:
fin.head()

host_is_superhost                      neighbourhood  \
2595                 f            New York, United States   
3831                 f  Brooklyn, New York, United States   
5121                 f                                NaN   
5178                 f            New York, United States   
5203                 f            New York, United States   

                  property_type        room_type  accommodates  bathrooms  \
2595           Entire apartment  Entire home/apt             2        NaN   
3831         Entire guest suite  Entire home/apt             3        NaN   
5121  Private room in apartment     Private room             2        NaN   
5178  Private room in apartment     Private room             2        NaN   
5203  Private room in apartment     Private room             1        NaN   

      bedrooms  beds                                          amenities  \
2595       NaN   1.0  ["Hot water", "Extra pillows and blankets", "O...   
3831       1.0   3.0  ["Hot water", "Shampoo", "Baby safety gates", ...   
5121       1.0   1.0  ["Wifi", "Kitchen", "Heating", "Air conditioni...   
5178       1.0   1.0  ["Wifi", "Heating", "Refrigerator", "Shampoo",...   
5203       1.0   1.0  ["Wifi", "Heating", "Hot water", "Shampoo", "F...   

        price  number_of_reviews_ltm  number_of_reviews_l30d last_review  \
2595  $175.00                      0                       0  2019-11-04   
3831   $74.00                     77                       4  2020-11-22   
5121   $60.00                      0                       0  2019-12-02   
5178   $65.00                     16                       0  2020-09-25   
5203   $75.00                      0                       0  2017-07-21   

      review_scores_rating  review_scores_accuracy  review_scores_cleanliness  \
2595                  94.0                     9.0                        9.0   
3831                  89.0                     9.0                        9.0   
5121                  90.0                     8.0                        8.0   
5178                  84.0                     9.0                        8.0   
5203                  98.0                    10.0                       10.0   

      review_scores_checkin  review_scores_communication  \
2595                   10.0                         10.0   
3831                    9.0                          9.0   
5121                   10.0                         10.0   
5178                    9.0                          9.0   
5203                   10.0                         10.0   

      review_scores_location  review_scores_value  
2595                    10.0                  9.0  
3831                    10.0                 10.0  
5121                     9.0                  9.0  
5178                    10.0                  9.0  
5203                    10.0                 10.0

In [29]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36923 entries, 2595 to 46941857
Data columns (total 76 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   listing_url                                   36923 non-null  object 
 1   scrape_id                                     36923 non-null  int64  
 2   last_scraped                                  36923 non-null  object 
 3   name                                          36910 non-null  object 
 4   description                                   35829 non-null  object 
 5   neighborhood_overview                         23446 non-null  object 
 6   picture_url                                   36923 non-null  object 
 7   host_id                                       36923 non-null  int64  
 8   host_url                                      36923 non-null  object 
 9   host_name                                     36914 non

In [ ]:


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, ])

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
X = np.array(ct.fit_transform(combined))



# Train Test Split 

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=41)

In [64]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, label_train)
print("The score for kNN is")
print("Training: {:6.2f}%".format(100*knn.score(X_train, label_train)))
print("Test set: {:6.2f}%".format(100*knn.score(X_test, label_test)))

The score for kNN is
Training: 100.00%
Test set:  93.33%


In [65]:
logit = LogisticRegression(C = 0.95)
logit.fit(X_train, label_train)
print("The score for logistic regression is")
print("Training: {:6.2f}%".format(100*logit.score(X_train, label_train)))
print("Test set: {:6.2f}%".format(100*logit.score(X_test, label_test)))

The score for logistic regression is
Training:  99.05%
Test set:  91.11%


In [66]:
# Let's do a prediction of the first 5 observations from logistic

logit.predict_proba(X_test[:5,])

array([[0.00101795, 0.57657677, 0.42240528],
       [0.00004629, 0.05857614, 0.94137757],
       [0.00000248, 0.02059551, 0.97940201],
       [0.00923726, 0.7729446 , 0.21781815],
       [0.00007883, 0.08641823, 0.91350293]])

In [67]:
from sklearn.metrics import confusion_matrix

print("kNN confusion matrix: \n\n", confusion_matrix(label_test, knn.predict(X_test)))

kNN confusion matrix: 

 [[11  0  0]
 [ 0 16  2]
 [ 0  1 15]]


In [58]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
                                     
X = np.array(ct.fit_transform(combined))

In [60]:
print(X)

[[1.0 0.0 0.0 ... 10950.0 410625.0 64231.0]
 [1.0 0.0 0.0 ... 365.0 410625.0 28177.0]
 [0.0 0.0 1.0 ... 10950.0 266450.0 21900.0]
 ...
 [0.0 0.0 0.0 ... 365.0 410625.0 18130.0]
 [1.0 0.0 0.0 ... 1460.0 32850.0 107675.0]
 [1.0 0.0 0.0 ... 365.0 410625.0 182500.0]]


In [75]:
df_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36923 entries, 2595 to 46941857
Data columns (total 73 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   listing_url                                   36923 non-null  object 
 1   scrape_id                                     36923 non-null  int64  
 2   last_scraped                                  36923 non-null  object 
 3   name                                          36910 non-null  object 
 4   description                                   35829 non-null  object 
 5   neighborhood_overview                         23446 non-null  object 
 6   picture_url                                   36923 non-null  object 
 7   host_id                                       36923 non-null  int64  
 8   host_url                                      36923 non-null  object 
 9   host_name                                     36914 non

In [76]:
df_list.head(50)

listing_url       scrape_id last_scraped  \
id                                                                       
2595    https://www.airbnb.com/rooms/2595  20201210194816   2020-12-11   
3831    https://www.airbnb.com/rooms/3831  20201210194816   2020-12-11   
5121    https://www.airbnb.com/rooms/5121  20201210194816   2020-12-11   
5178    https://www.airbnb.com/rooms/5178  20201210194816   2020-12-11   
5203    https://www.airbnb.com/rooms/5203  20201210194816   2020-12-11   
5803    https://www.airbnb.com/rooms/5803  20201210194816   2020-12-11   
6848    https://www.airbnb.com/rooms/6848  20201210194816   2020-12-11   
6872    https://www.airbnb.com/rooms/6872  20201210194816   2020-12-11   
6990    https://www.airbnb.com/rooms/6990  20201210194816   2020-12-11   
7097    https://www.airbnb.com/rooms/7097  20201210194816   2020-12-11   
7750    https://www.airbnb.com/rooms/7750  20201210194816   2020-12-11   
7801    https://www.airbnb.com/rooms/7801  20201210194816   2020-12-11   
8490    https://www.airbnb.com/rooms/8490  20201210194816   2020-12-11   
9357    https://www.airbnb.com/rooms/9357  20201210194816   2020-12-11   
9657    https://www.airbnb.com/rooms/9657  20201210194816   2020-12-11   
9704    https://www.airbnb.com/rooms/9704  20201210194816   2020-12-11   
10452  https://www.airbnb.com/rooms/10452  20201210194816   2020-12-11   
10962  https://www.airbnb.com/rooms/10962  20201210194816   2020-12-11   
11943  https://www.airbnb.com/rooms/11943  20201210194816   2020-12-11   
12192  https://www.airbnb.com/rooms/12192  20201210194816   2020-12-11   
12343  https://www.airbnb.com/rooms/12343  20201210194816   2020-12-11   
12937  https://www.airbnb.com/rooms/12937  20201210194816   2020-12-11   
12940  https://www.airbnb.com/rooms/12940  20201210194816   2020-12-11   
13121  https://www.airbnb.com/rooms/13121  20201210194816   2020-12-11   
13267  https://www.airbnb.com/rooms/13267  20201210194816   2020-12-11   
13394  https://www.airbnb.com/rooms/13394  20201210194816   2020-12-11   
13808  https://www.airbnb.com/rooms/13808  20201210194816   2020-12-11   
14290  https://www.airbnb.com/rooms/14290  20201210194816   2020-12-11   
14314  https://www.airbnb.com/rooms/14314  20201210194816   2020-12-11   
14322  https://www.airbnb.com/rooms/14322  20201210194816   2020-12-11   
15341  https://www.airbnb.com/rooms/15341  20201210194816   2020-12-11   
15385  https://www.airbnb.com/rooms/15385  20201210194816   2020-12-11   
15396  https://www.airbnb.com/rooms/15396  20201210194816   2020-12-11   
15711  https://www.airbnb.com/rooms/15711  20201210194816   2020-12-11   
16326  https://www.airbnb.com/rooms/16326  20201210194816   2020-12-11   
16338  https://www.airbnb.com/rooms/16338  20201210194816   2020-12-11   
16580  https://www.airbnb.com/rooms/16580  20201210194816   2020-12-11   
16595  https://www.airbnb.com/rooms/16595  20201210194816   2020-12-11   
16821  https://www.airbnb.com/rooms/16821  20201210194816   2020-12-11   
16974  https://www.airbnb.com/rooms/16974  20201210194816   2020-12-11   
17037  https://www.airbnb.com/rooms/17037  20201210194816   2020-12-11   
17693  https://www.airbnb.com/rooms/17693  20201210194816   2020-12-11   
17747  https://www.airbnb.com/rooms/17747  20201210194816   2020-12-11   
18127  https://www.airbnb.com/rooms/18127  20201210194816   2020-12-11   
18195  https://www.airbnb.com/rooms/18195  20201210194816   2020-12-11   
18198  https://www.airbnb.com/rooms/18198  20201210194816   2020-12-11   
18728  https://www.airbnb.com/rooms/18728  20201210194816   2020-12-11   
18764  https://www.airbnb.com/rooms/18764  20201210194816   2020-12-11   
18961  https://www.airbnb.com/rooms/18961  20201210194816   2020-12-11   
19159  https://www.airbnb.com/rooms/19159  20201210194816   2020-12-11   

                                                    name  \
id                                                         
2595                               Skylit Midtown Castle   
3